### ISSUE TITLE
Recategorize.py Makes it to Wrting report stage then errors

### ISSUE THREAD

**Issue by turnerdb** [ChrisTruncer/EyeWitness#319] opened 2018-03-13 18:26 UTC
## OS Used - ALL Information (architecture, linux flavor, etc.)
kali . 2017.1

## Pastebin link to error you are encountering
6350/6352
Writing report
Traceback (most recent call last):
  File "./Recategorize.py", line 50, in <module>
    sort_data_and_write(cli_parsed, results)
  File "/opt/EyeWitness/modules/reporting.py", line 200, in sort_data_and_write
    html += obj.create_table_html()
  File "/opt/EyeWitness/modules/objects.py", line 233, in create_table_html
    self.sanitize(self.page_title))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 16: ordinal not in range(128)

## Expected behavior (vs. what you encountered)
Expected report to be generated

## Any additional information
This is in response to a closed issue where you informed me to use the recategorize.py script to rescan the one that got hung up on the last two IPs.

**Comment by ChrisTruncer** [comment] 2018-03-13 23:16
Are you able to share the .db file with me (privately if need be)? I can see it’s a Unicode issue, but will be hard to reproduce without it.

**Comment by turnerdb** [comment] 2018-03-14 15:47
I’m going to try and scrub the data as there is sensitive info.  What tool can I use to read those dB files.  

Also I am working to convert an xls to xml to be ingested by eyewitness but get the “xml film you provided does not contain any active web servers”. What field(s) do I need to have in the xml in order for eyewitness to recognize them and go after them?

Thanks for all the help with this. We all really appreciate it. 

Devin.

**Comment by ChrisTruncer** [comment] 2018-03-14 16:10
It’s just a SQLite dB, so any tool that supports that should allow you to open it.

The only XML formats which are currently supported are NMap and Nessus (.nessus), so it’s have to be in their file format. It’s likely easier to write out to a single file (if possible) containing urls on a new line.

**Comment by turnerdb** [comment] 2018-03-14 16:27
How do I view it so the blobs show up as editable data?  I assume the ips would be in there. That’s what I need to remove.

**Comment by ChrisTruncer** [comment] 2018-03-15 22:50
I'm happy to say I think I recreated this. I ran into a similar issue with recategorize and believe it should now be working (patch fixed my issue). Please pull the latest version and let me know if recategorize.py will work with your ew.db file.

**Comment by turnerdb** [comment] 2018-03-17 06:41
Awesome!   Thank you!

**Comment by ChrisTruncer** [comment] 2018-03-18 22:11
It fixed on your side?

**Comment by turnerdb** [comment] 2018-03-19 01:00
Haven’t had a chance to update yet.  Be getting to it Monday.  

Thanks for checking in!

Devin.

**Comment by turnerdb** [comment] 2018-03-20 15:08
One other quick question.  You sent out a tweet taking about reporting being set back to the old way.  Can you elaborate on that briefly?

Thanks.

**Comment by turnerdb** [comment] 2018-03-20 15:54
Also what is the best practice when it comes to updating Eyewitness?

**Comment by ChrisTruncer** [comment] 2018-04-05 12:34
Closing this since the issue should be fixed.

Report is just in its old format, but the newer format is still available in a different branch. Best way to update EyeWitness is to perform a "git pull" within the eyewitness directory

**Closed by ChrisTruncer** 2018-04-05 12:34 UTC

**Comment by turnerdb** [comment] 2018-04-11 21:43
I apologize for my lack of git knowledge on this part but how would I use a git pull to update the version I am using in our environment.  So when you release a new feature or bug fix I don’t have download the whole thing and run the setup script each change. 

Thanks.
