### ISSUE TITLE
Fatal IO error

### ISSUE THREAD

**Issue by leebaird** [ChrisTruncer/EyeWitness#205] opened 2016-07-28 14:27 UTC
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali rolling

./EyeWitness.py --all-protocols -f /root/Desktop/80.txt
(scan runs with no issues)

[*] Done! Report written in the /opt/EyeWitness/07282016_101108 folder!
Would you like to open the report now? [Y/n] python: Fatal IO error 0 (Success) on X server :1028.

I did not have the chance to make a choice after the scan completed because of the error.

**Comment by ChrisTruncer** [comment] 2016-07-28 18:15
Does this happen every time you run --all-protocols, is it specific to just that file input you're using?

**Comment by leebaird** [comment] 2016-07-28 19:15
I've tested the same scan against 4 different files. All had the same error

**Comment by ChrisTruncer** [comment] 2016-07-29 22:53
I think I might end up taking the --all-protocols out and having users just specify what they want scanned.  If you run your scans individually, does it all work in that case?  Or can you isolate the issue to a single protocol?

**Comment by leebaird** [comment] 2016-07-29 23:55
I retested today using just --web and it worked fine.

**Comment by ChrisTruncer** [comment] 2016-07-30 14:01
Did you run vnc or rdp against it? I'm trying to find if the issue is a single protocol

**Comment by leebaird** [comment] 2016-07-30 14:15
All 4 of the files I was testing against only had port 80 open.

**Comment by ChrisTruncer** [comment] 2016-08-01 02:58
Sorry, but I can't seem to recreate this.  I've tested on both Debian (stable) and the latest version of Kali.  When giving file input and telling EyeWitness to do --all-protocols, it just screenshots what it sees and then waits for input if I'd like to open the report or not and doesn't give a fatal error.

**Comment by ChrisTruncer** [comment] 2016-08-02 20:24
If you have any other ways to try to get this to reproduce, I'll be happy to look into this.  Otherwise I will close this soon.  Unfortunately I can't seem to make this happen on my Kali system.

**Closed** 2016-08-04 16:03 UTC
