### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by korang** [ChrisTruncer/EyeWitness#118] opened 2015-02-23 03:42 UTC
Trying tun run against a list of 74 websites. Hit number 22 and get Segmentation fault: 11.  I am on MAC OSX 10.10.2.  Python 2.7.9.

**Comment by korang** [comment] 2015-02-23 03:48
I also see there error a couple times during this scan:  WARNING:qt:QFont::setPixelSize: Pixel size <= 0 (0)

**Comment by ChrisTruncer** [comment] 2015-02-23 13:24
Hey there,

I can't really test in that environment unfortunately, so it'll be hard for me to re-create.

For the warning, I am looking into that.  I know that started happening when I upgraded the version of Ghost everyone is using.  I'm trying to figure out how to suppress that.  In the meantime, try the beta version that is in a different branch under the EyeWitness Repo.  It should use Selenium, vs. ghost by default (unless you use --headless).  Selenium is a lot better and more stable.

**Comment by ChrisTruncer** [comment] 2015-02-23 13:47
Looking into that message, it may just be a QT debug message.  There seems to be a lot of threads out there on this message appearing, but not a solid way to fix it yet.

**Comment by korang** [comment] 2015-02-23 14:24
Trying to screenshot https://199.38.149.24:443
Traceback (most recent call last):
  File "EyeWitness.py", line 2642, in <module>
    selenium_object = create_selenium_driver(cli_parsed)
  File "EyeWitness.py", line 335, in create_selenium_driver
    driver = webdriver.Firefox(profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.binary, timeout),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/firefox/extension_connection.py", line 47, in __init__
    self.binary.launch_browser(self.profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 65, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 88, in _start_from_profile_path
    env=self._firefox_env).communicate()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ChrisTruncer** [comment] 2015-02-23 14:26
ok, thanks for that, checking it out

**Comment by ChrisTruncer** [comment] 2015-02-23 14:37
I just pushed a fix that will catch that error (I believe).  Looks like the cause was because the SSL site wasn't able to establish a SSL connection.

**Comment by ChrisTruncer** [comment] 2015-02-23 14:38
It's in the Shmoo branch, let me know if that fixes it for you

**Comment by korang** [comment] 2015-02-23 14:45
Traceback (most recent call last):
  File "EyeWitness.py", line 2644, in <module>
    selenium_object = create_selenium_driver(cli_parsed)
  File "EyeWitness.py", line 335, in create_selenium_driver
    driver = webdriver.Firefox(profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.binary, timeout),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/firefox/extension_connection.py", line 47, in __init__
    self.binary.launch_browser(self.profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 65, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 88, in _start_from_profile_path
    env=self._firefox_env).communicate()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by korang** [comment] 2015-02-23 14:45
I may just need to abondon my macbook and try my kali instance

**Comment by ChrisTruncer** [comment] 2015-02-23 14:48
Did you re-run the setup script in the new branch?  It has all the additional imports and everything required for the Shmoo branch, so it is different.

**Comment by korang** [comment] 2015-02-23 14:53
Ahh ok let me do that

**Comment by korang** [comment] 2015-02-23 14:55
[Error]:  is not supported by this setup script.
[Error]: To use EyeWitness, manually install python, PyQt4.
[Error]: Install ghost.py from https://github.com/ChrisTruncer/Ghost.py.git

**Comment by ChrisTruncer** [comment] 2015-02-23 14:57
Ah, yeah.  So it install's a lot of dependencies via apt, so obviously that would be a problem on Mac.  It's really designed to be run on Linux simply because of the package management.  You could try installing the dependencies manually, or it will be easier for linux, Kali if possible.

**Comment by korang** [comment] 2015-02-23 17:08
Will look at script later and see if I can manually do it on the mac.

**Comment by ChrisTruncer** [comment] 2015-02-26 17:42
I'm going to go ahead and close this out, hopefully everything should be ok for you.  If you run into any other issues, feel free to open another issue ticket.  Thanks for all your help letting me know if any issues you run into.

**Closed by ChrisTruncer** 2015-02-26 17:42 UTC
