### ISSUE TITLE
Cannot take screenshots of RDP services on fresh Kali installs

### ISSUE THREAD

**Issue by absane** [ChrisTruncer/EyeWitness#169] opened 2016-01-14 22:44 UTC
I've tried running EyeWitness on multiple Kali Linux installs on two different computers and get the same error: **Xlib:  extension "RANDR" missing on display**. In every instance EyeWitness cannot grab screenshots of the RDP services.

Command used
`./EyeWitness.py -f nmap.xml --all-protocols -d screens --no-prompt`

Output
```
Directory Exists! Do you want to overwrite? [y/n] y
Detected nmap xml file

Starting Web Requests (1 Hosts)
Attempting to screenshot http://x.x.x.x

Starting VNC/RDP Requests (4 Hosts)
Xlib:  extension "RANDR" missing on display ":1005".
[*] Connecting to x.x.x.x (RDP)
[*] Connecting to x.x.x.x (RDP)
[*] Connecting to x.x.x.x (RDP)
[*] Connecting to x.x.x.x (RDP)
Finished in 4.91123390198 seconds
```

Any ideas on where to look or am I the only one with this issue? I tried tracing the issue myself but cannot come up with a root cause. In my final test I downloaded a fresh Kali ISO and a fresh VMWare image. In both instances I ran into this issue.

Edit: Failed to mention that I am using Kali 2.0.

**Comment by absane** [comment] 2016-01-15 12:17
Did some more prodding and it seems that the problem might lie in how EW parses XMLs from Nmap. The system I am trying to screenshot has RDP on 4 separate ports with one of them being the standard 3389. I was able to hack my way around this issue by dumping all URLs and IP:port combinations into a text file and using the -f option in EQ to screenshot everything.  However, this hack does slow down the process quite a bit with multiple retires and errors since EW assumes all port combinations are also HTTP or VNC (with --all-protocols option).

**Comment by ChrisTruncer** [comment] 2016-01-15 17:20
Oh, interesting.  Thanks for taking the time to look into it, I appreciate it.  Would you by chance be able to send me the nmap xml output so I can test on my end?  It could be sent to my private e-mail so it’s not public, but I also understand if you’re not able to do that.

Regardless, I’ll try to check into this and confirm the cause.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer

On January 15, 2016 at 5:17:48 AM, absane (notifications@github.com) wrote:

Did some more prodding and it seems that the problem might lie in how EW parses XMLs from Nmap. The system I am trying to screenshot has RDP on 4 separate ports with one of them being the standard 3389. I was able to hack my way around this issue by dumping all URLs and IP:port combinations into a text file and using the -f option in EQ to screenshot everything. However, this hack does slow down the process quite a bit with multiple retires and errors since EW assumes all port combinations are also HTTP or VNC (with --all-protocols option).

**Comment by absane** [comment] 2016-01-15 22:43
Yes, if I can get your e-mail I can do that,

**Comment by ChrisTruncer** [comment] 2016-01-15 22:50
You can e-mail it to me at eyewitness {at} christophertruncer [dot] com


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer

On January 15, 2016 at 3:43:58 PM, absane (notifications@github.com) wrote:

Yes, if I can get your e-mail I can do that,

**Comment by ChrisTruncer** [comment] 2016-01-18 03:39
I'm going to close this out here and we can continue on e-mail.

**Closed by ChrisTruncer** 2016-01-18 03:39 UTC
