### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by rkornmeyer** [ChrisTruncer/EyeWitness#123] opened 2015-03-05 15:30 UTC
I've had it happen a couple times where if i attempt to scan a large list of hosts, 248 + it results in a segfault. I'm not sure if this is eyefinity, ghost or kali.

**Comment by ChrisTruncer** [comment] 2015-03-05 15:44
Can you try using selenium within the beta branch?  The issue, I'm pretty certain, is with Ghost.  It's actually why I'm moving away from using it primarily in EyeWitness. It does work well, but will also randomly encounter issues.  I'm leaving it in the beta branch, and will leave it in there in the event someone needs/wants to use it for some reason, but by default the --web flag will use Selenium now which should be much more stable.

Can you try using that and let me know how it goes?

**Comment by anthonynena** [comment] 2015-03-26 18:40
Having this issue also.
Where is the beta branch?  I'm only seeing master...

**Comment by anthonynena** [comment] 2015-03-26 18:49
I'm also trying to use a large list of URL's.  Doesn't seem to be an issue with the host, because when I run eyewitness against it by itself, i don't get the segmentation fault message.  This was 72/8471 URLs. I can break it up into files of 50 hosts at a time but will be less convenient when reviewing the results.

**Comment by ChrisTruncer** [comment] 2015-03-26 19:00
I'm getting the beta branch re-added.  I didn't see anyone using it, so I brought it down.  We're still testing with it, but IMO it's more stable since it tries to promote using selenium vs. ghost.

**Comment by anthonynena** [comment] 2015-03-26 19:25
Ok perfect.  I split up the commands into 50 URLs at a time, and still hitting the segmentation fault every other command it seems.

**Comment by ChrisTruncer** [comment] 2015-03-26 19:27
Can you see if it is a specific URL or anything like that?  Sounds like something that should be reported up the chain to the ghost library developer.

**Comment by ChrisTruncer** [comment] 2015-03-26 19:43
Beta branch is pushed.  Re-run the setup script to add in the new dependencies.  You can still provide a file for input with -f.  For web screenshots, use --web to use Selenium (much better IMO).  However, if you need headless, you can use ghost with --headless

**Comment by anthonynena** [comment] 2015-03-26 20:45
Not any specific URL.  Seems to happen every once in a while with random IP's and doesn't seem to matter whether it's 443 or 80, SSL or not.  I downloaded the beta and using selenium right now.   I'll let you know if there are any issues.

**Comment by anthonynena** [comment] 2015-03-27 16:46
I'm not receiving the segmentation fault with the beta and --web flag, but the command started getting stuck after the 300th URL.  CTRL+C moves it to the next URL and it will continue for another couple URL's then get stuck again.

**Comment by ChrisTruncer** [comment] 2015-03-27 16:58
Hm, not sure.  Since it is actually using your browser, it possible it's just taking a while to load those pages?

**Comment by anthonynena** [comment] 2015-03-27 16:59
No, it remains stuck for hours if I would let it.
Is there any debugging output that I can provide you?

**Comment by ChrisTruncer** [comment] 2015-03-27 17:12
Hm, are the sites you are trying to scan public?  If so, I can try to run the same scan and check out the issue.

**Comment by anthonynena** [comment] 2015-03-27 19:57
I may have noticed a trend...every time an http redirects to https, the selenium browser follows the redirect then gets stuck, and doesn't move onto the next URL.

This only happens when I specify the port number as follows:
http://149.122.97.72:80
./EyeWitness.py --single http://149.122.97.72:80 --web

When I remove the appended port number, selenium closes and the command finishes.
http://149.122.97.72
./EyeWitness.py --single http://149.122.97.72 --web

Another thing that is weird is that i can specify the port with a well known site like accounts.google.com and it works fine as well.
./EyeWitness.py --single http://accounts.google.com:80 --web

In my huge list of URL's there are some web servers hosting over non-standard ports. Is there another way to specify non-standard ports that would be compatible?

**Comment by ChrisTruncer** [comment] 2015-03-31 23:59
Hm.. that's really a interesting case.  Did that trend continue?

**Comment by rvazarkar** [comment] 2015-05-22 20:48
As far as I know, this issue should be fixed in the nuke_it_all branch, which should eventually become master. It looks like the issue was directly related to the port numbers, so we rolled some logic to strip ports 80 and 443. If you can reproduce this issue, let me know

**Comment by ChrisTruncer** [comment] 2015-06-15 13:11
This should now be good

**Closed by ChrisTruncer** 2015-06-15 13:11 UTC
